### PR TITLE
Converts configuration to YAML

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
@benjwadams

**Comment by lukecampbell** [comment]
Fixes #378

**Comment by daf** [comment]
Still using supervisord?  Should adjust the template as part of these changes too.

**Comment by benjwadams** [comment]
Can we really commit to the same yaml file we'll be using in to configure?  Every time we make a change to the yaml file, it'll show up and if we want to pull down changes it will cause merge conflicts.  Maybe make a config.yml.example and then add config.yml to .gitignore?

**Comment by lukecampbell** [comment]
I think you may be overthinking it. On production you _could_ just make a branch with the configuration changes and call the branch "production" and just rebase it on the latest every time.

Or, you could just git stash, then pull then git stash apply.

There's any number of possibilities.

The point of this is so that developers can clone the project and actively start developing with minimal changes and the configuration is intuitive. The environment variables are essentially hidden, and unless you know where to look and understand the relationship between supervisor, gunicorn and the Flask app, you'll waste hours trying to configure the application.

**Comment by lukecampbell** [comment]
@daf yeah, I already have those changes staged on production.

**Comment by daf** [comment]
A lot of projects have the VCS tracked file called `config.yaml.example` with instructions to make you copy it to the right place, with `config.yaml` specifically ignored.  That might solve some headaches.

Also why are the supervisor template changes not in this repo?

**Comment by benjwadams** [comment]
See also https://gist.github.com/canton7/1423106

**Comment by lukecampbell** [comment]
@daf the supervisor templates haven't come from catalog in a WHILE they come from deploy-fabs.

**Comment by lukecampbell** [comment]
The background on that is that fabric broke last year and no one has had the time to fix it, (or risk corrupting production).

**Comment by daf** [comment]
Hmm, I don't remember putting those in there (maybe you did), that's probably why I'm so confused.  You should likely delete [deploy/supervisord.conf](https://github.com/ioos/catalog/blob/master/deploy/supervisord.conf) then for lack of confusion.

**Pull request merged**
