### PR TITLE
Updates documentation for CKAN and registry

### PR DESCRIPTION
**Pull request by lukecampbell**
This commit has updated documentation for the system's schedule for
executing jobs. Documentation on how to use the Registry's API. It also
has a small section on the feedback button in the UI.

### CODE REVIEW

**Comment by lukecampbell** [comment]
This fixes https://github.com/ioos/catalog-ckan/issues/146

**Comment by lukecampbell** [comment]
This also fixes https://github.com/ioos/catalog/issues/30

**Comment by lukecampbell** [comment]
And #39

**Comment by mwengren** [comment]
@lukecampbell jeez, you are too fast for me today...

**Pull request merged**
